language: cpp

script:
 - "bash -ex .travis-ci.sh"

matrix:
  fast_finish: true
  include:
    # Clang won't work on Linux until -Wno-unused-local-typedefs is flagged by compiler not OS
    #- compiler: clang
    #  env: TASK='compile'
    - compiler: gcc
      env: TASK='compile' QT='qt4'
    - compiler: gcc
      env: TASK='compile' QT='qt5'

cache: apt

before_install:
 - sudo add-apt-repository ppa:h-rayflood/gcc-upper -y
 #- sudo add-apt-repository ppa:h-rayflood/llvm-upper -y
 - sudo add-apt-repository ppa:ubuntu-sdk-team/ppa -y
 - sudo apt-get update -qq
 - sudo apt-get install -qq gdb libasound2-dev libusb-dev libftdi-dev shared-mime-info libudev-dev libmad0-dev libsndfile1-dev liblo-dev libfftw3-dev
 # Install the relevant bits of Qt
 - if [ "QT" = "qt4" ]; then sudo apt-get install -qq libqt4-dev; fi
 - if [ "QT" = "qt5" ]; then sudo apt-get install -qq qt5-qmake libqt5-dev qtbase5-dev; fi
 # Start xvfb so tests don't fail
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
#g++-4.9 won't work on Ubuntu 12.04 that Travis currently uses
 - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
 - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
#Remove the old g++/gcc to ensure we're using the latest ones
 - if [ "$CXX" = "g++-4.8" ]; then sudo rm /usr/bin/g++; sudo rm /usr/bin/gcc; fi
#Report the compiler version
 - $CXX --version
